name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-06"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL ="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZDYxNWMwYzEtMzZlMi00ODIxLThhZjQtZjE4ZjU5MzFhNGU0IiwidGVuYW50X2lkIjoiMDcxYmNiYzg0N2ExOWNmY2Y1ODNiYzg1NzRjY2FhMzc5ODhhN2NiYTgzZTRhNjI0NmM2MTY3YjBhZmM3MmRiMiIsImludGVybmFsX3NlY3JldCI6ImMzYTNhMzhjLTBkMDQtNGJkZC1hNTM5LWQ5NmQ5MDdjZmU1YSJ9.DQnGEHxn2bK7oYsV2ApNPrXZD73mOcteOkgHYZfoUAo"
PORT = "3000"
CORS_ORIGIN = "*"

# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1